### ISSUE TITLE
Does this project exclude Hactoberfest?

### ISSUE THREAD

**Issue by gympohnpimol** [Aman22sharma/Hacktoberfest2020_beginner#238]
<img width="1036" alt="Screen Shot 2564-10-12 at 20 50 33" src="https://user-images.githubusercontent.com/56881546/136968897-1b70a04b-54c6-4d72-b238-145cd75ea2bd.png">

**Comment by Aman22sharma** [comment]
@gympohnpimol Hey we figure out this issue we have already reported this issue to hacktoberfest support team

**Comment by gympohnpimol** [comment]
> @gympohnpimol Hey we figure out this issue we have already reported this issue to hacktoberfest support team

I am waiting for hearing any update from your team.
Hope it gonna be well.

**Comment by Aman22sharma** [comment]
@gympohnpimol yaa sure we will resolve this issue as soon as possible and inform you soon thanks

**Comment by JoaquinMontesinos** [comment]
@Aman22sharma For me appear same popup. I am waiting for the response too

**Comment by Arayan1906** [comment]
ya mee too waiting for response , I submitted 3 pr's all got excluded.

**Comment by Arayan1906** [comment]
Any updates? @Aman22sharma

**Comment by gympohnpimol** [comment]
@Arayan1906 I found there are many excluded projects this year. 😭😭😭

**Comment by Arayan1906** [comment]
Yeah , in fact I have made nearly 22 pull requests, only one is maturing currently , all got excluded. 3 were in this repository itself. @gympohnpimol
