### ISSUE TITLE
Add your python concept

### ISSUE THREAD

**Issue by Aman22sharma** [Aman22sharma/Hacktoberfest2020_beginner#9]
**This issue is only for beginners.**
In the Python3-Learn directory. You can add any python3 concepts. 
Follow the contribution guidelines under [README.md](https://github.com/Aman22sharma/Hacktoberfest2020_beginner/blob/main/README.md)

- Write a proper commit message - "Added-Python3-Python3conceptname"
                                                          _For_ example - Added-python3-variables

**Comment by Pankaj05011998** [comment]
Hi, I have added code. Please check it #9

**Comment by Aman22sharma** [comment]
@Pankaj05011998 You didn't push your code yet. Push your changes and create a pull request.

**Comment by Pankaj05011998** [comment]
Hey, check my pull request

**Comment by Aman22sharma** [comment]
Guy's I will definitely review and approved all PRs. I am a bit busy I have my job also that's why it looks some times

**Comment by durgeshahire07** [comment]
hello @Aman22sharma , i have added a Python3 concept please check it #22

**Comment by memegamer138** [comment]
Hi @Aman22sharma I added a new concept. Branch #43 . Please review it.

**Comment by Aman22sharma** [comment]
Closed
